import json
import hashlib
from datetime import datetime

def generate_audit_receipt(job_id: str, filename: str, target_column: str, protected_attributes: list, disparities: dict, proxies: list) -> dict:
    """
    Generates a tamper-evident audit receipt.
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    
    payload = {
        "job_id": job_id,
        "timestamp": timestamp,
        "dataset_name": filename,
        "target_column": target_column,
        "protected_attributes_scanned": protected_attributes,
        "disparity_summary": {attr: data["disparity_score"] for attr, data in disparities.items()},
        "proxy_risks_found": len(proxies),
        "status": "COMPLETED"
    }
    
    # Create deterministic hash for tamper evidence
    payload_str = json.dumps(payload, sort_keys=True)
    receipt_hash = hashlib.sha256(payload_str.encode('utf-8')).hexdigest()
    
    return {
        "receipt": payload,
        "signature_hash": receipt_hash,
        "algorithm": "SHA-256"
    }

def generate_fairness_passport(job_id: str, filename: str, target_column: str, protected_attributes: list, disparities: dict, proxies: list, explanation: str, receipt_hash: str) -> str:
    """
    Generates a Markdown document (Fairness Passport) for compliance teams.
    """
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    md = f"""# Fairness Passport
**Audit Job ID:** `{job_id}`
**Timestamp:** `{timestamp}`
**Target System/Dataset:** `{filename}`
**Outcome Variable:** `{target_column}`
**Receipt Signature (SHA-256):** `{receipt_hash}`

---

## 1. Executive Summary
{explanation if explanation else "No summary provided by AI Inspector."}

---

## 2. Protected Attribute Disparity Risk
"""
    for attr, data in disparities.items():
        md += f"### {attr.capitalize()} (Risk: {data['risk_level']})\n"
        md += f"- **Max Disparity Difference:** {data['disparity_score']:.3f}\n"
        md += "- **Subgroup Breakdown:**\n"
        for sg in data['subgroups']:
            if sg:
                md += f"  - {sg['subgroup']}: {sg['selection_rate']:.2%} selection rate (n={sg['count']})\n"
        md += "\n"

    md += """## 3. Proxy Bias Detection
"""
    if proxies:
        md += "The following features were identified as potentially carrying indirect signals for protected traits:\n"
        for px in proxies:
            md += f"- **{px['proxy_feature']}** masks **{px['protected_attribute']}** (Severity: {px['severity']}, Score: {px['correlation_score']})\n"
    else:
        md += "No high-risk proxy variables detected.\n"
        
    md += """
---
*Generated by FairLens Studio Engine.*
"""
    return md
