import json
import hashlib
from datetime import datetime

def generate_audit_receipt(job_id: str, filename: str, target_column: str, protected_attributes: list, disparities: dict, proxies: list) -> dict:
    """
    Generates a tamper-evident audit receipt.
    """
    timestamp = datetime.utcnow().isoformat() + "Z"
    
    payload = {
        "job_id": job_id,
        "timestamp": timestamp,
        "dataset_name": filename,
        "target_column": target_column,
        "protected_attributes_scanned": protected_attributes,
        "disparity_summary": {attr: data["disparity_score"] for attr, data in disparities.items()},
        "proxy_risks_found": len(proxies),
        "status": "COMPLETED"
    }
    
    # Create deterministic hash for tamper evidence
    payload_str = json.dumps(payload, sort_keys=True)
    receipt_hash = hashlib.sha256(payload_str.encode('utf-8')).hexdigest()
    
    return {
        "receipt": payload,
        "signature_hash": receipt_hash,
        "algorithm": "SHA-256"
    }

def generate_fairness_passport(job_id: str, filename: str, target_column: str, protected_attributes: list, disparities: dict, proxies: list, explanation: dict | None, receipt_hash: str, simulation: dict | None = None) -> str:
    """
    Generates a Markdown document (Fairness Passport) for compliance teams.
    """
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    # Calculate a simple risk grade based on max disparity
    max_d = max([d['disparity_score'] for d in disparities.values()]) if disparities else 0
    grade = "A" if max_d < 0.05 else "B" if max_d < 0.1 else "C" if max_d < 0.2 else "D" if max_d < 0.4 else "F"
    
    md = f"""# Fairness Passport
**Final Risk Grade: {grade}**
**Audit Job ID:** `{job_id}`
**Timestamp:** `{timestamp}`
**Target System/Dataset:** `{filename}`
**Outcome Variable:** `{target_column}`
**Receipt Signature (SHA-256):** `{receipt_hash}`

---

## 1. Executive Summary (AI Auditor)
{explanation.get('summary', 'No summary provided.') if explanation else "No summary provided by AI Inspector."}

### Real-World Impact
{explanation.get('impact', 'N/A') if explanation else "N/A"}

---

## 2. Protected Attribute Disparity Risk
"""
    for attr, data in disparities.items():
        md += f"### {attr.capitalize()} (Risk: {data['risk_level']})\n"
        md += f"- **Max Disparity Difference:** {data['disparity_score']:.3f}\n"
        md += "- **Subgroup Breakdown:**\n"
        for sg in data['subgroups']:
            if sg:
                md += f"  - {sg['subgroup']}: {sg['selection_rate']:.2%} selection rate\n"
        md += "\n"

    md += """## 3. Proxy Bias Detection
"""
    if proxies:
        md += "The following features were identified as potentially carrying indirect signals for protected traits:\n"
        for px in proxies:
            md += f"- **{px['proxy_feature']}** masks **{px['protected_attribute']}** (Severity: {px['severity']}, Score: {px['correlation_score']})\n"
    else:
        md += "No high-risk proxy variables detected.\n"
        
    if simulation:
        md += f"""
---

## 4. Bias Mitigation Simulation (Threshold Adjustment)
By applying per-subgroup threshold tuning, we simulated a potential **{simulation['improvement']}% improvement** in parity.

### Simulated Parity Delta:
- **Baseline Disparity (Avg):** {np_mean([d['disparity_score'] for d in simulation['before'].values()]):.3f}
- **Mitigated Disparity (Avg):** {np_mean([d['disparity_score'] for d in simulation['after'].values()]):.3f}
"""

    if explanation and explanation.get('recommendations'):
        md += "\n## 5. Technical Recommendations\n"
        for rec in explanation['recommendations']:
            md += f"- {rec}\n"
            
    md += """
---
*Generated by FairLens Studio Engine. This passport serves as a point-in-time compliance artifact.*
"""
    return md

def np_mean(data):
    if not data: return 0
    return sum(data) / len(data)
